version: '3.4'

networks:
  vuttr:
    ipam:
      config:
      - subnet: 172.21.1.0/24

services:
  api:
    container_name: api
    networks:
      vuttr:
        ipv4_address: 172.21.1.7
    volumes:
    - ./:/ws
    image: node:8.16.0-alpine
    working_dir: /ws/api
    entrypoint: /bin/sh -c 'npm install && npm start; tail -f /ws/docker-compose.yml'
    environment:
    - HOST=0.0.0.0
    - PORT=4000
    ports:
    - 4000:4000

  e2e:
    container_name: e2e
    networks:
      vuttr:
        ipv4_address: 172.21.1.2
    volumes:
    - ./:/ws
    image: node:8.16.0-alpine
    working_dir: /ws/e2e
    entrypoint: /bin/sh -c 'npm install; tail -f /ws/docker-compose.yml'
    environment:
    - APP_URL=http://172.21.1.3:4200

  app:
    container_name: app
    networks:
      vuttr:
        ipv4_address: 172.21.1.3
    volumes:
    - ./:/ws
    image: node:8.16.0-alpine
    working_dir: /ws/app
    environment:
    - PORT=4200
    - HOST=0.0.0.0
    - REACT_APP_API=http://172.21.1.7:4000
    ports:
    - 4200:4200
    - 4300:4300
    - 4400:4400
    entrypoint: /bin/sh -c '/ws/app.sh; tail -f /ws/docker-compose.yml'

  hub:
    container_name: hub
    image: selenium/hub:2.53.1-beryllium
    environment:
    - TZ=BRT3BRST,M11.1.6/23:59:59,M2.3.6/23:59:59
    ports:
     - 4444:4444
    networks:
      vuttr:
        ipv4_address: 172.21.1.4

  firefox:
    container_name: firefox
    image: selenium/node-firefox:2.53.1-beryllium
    environment:
    - HUB_PORT_4444_TCP_ADDR=hub
    - TZ=BRT3BRST,M11.1.6/23:59:59,M2.3.6/23:59:59
    ports:
    - 9000
    depends_on:
    - app
    networks:
      vuttr:
        ipv4_address: 172.21.1.5

  chrome:
    container_name: chrome
    image: selenium/node-chrome:2.53.1-beryllium
    ports:
    - 9000
    environment:
    - HUB_PORT_4444_TCP_ADDR=hub
    - TZ=BRT3BRST,M11.1.6/23:59:59,M2.3.6/23:59:59
    depends_on:
    - app
    networks:
      vuttr:
        ipv4_address: 172.21.1.6
